spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.25.104.223:33060/agencia_viajes?serverTimezone=UTC
    username: root
    password: example
  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8081
eureka:
  instance:
    instance-id: servicio-vuelo
    hostname: 172.25.104.223
  client:
    serviceUrl:
      defaultZone: http://172.25.104.223:8761/eureka
