spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.25.104.223:33060/agencia_viajes?serverTimezone=UTC
    username: root
    password: example
  jpa:
    hibernate:
      naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 8082
eureka:
  instance:
    instance-id: servicio-reserva
    hostname: 172.25.104.223
  client:
    serviceUrl:
      defaultZone: http://172.25.104.223:8761/eureka
app:
  url-servicio-vuelo: http://172.25.104.223:9000/wsvuelo
  url-servicio-hotel: http://172.25.104.223:9000/wshotel
